import { PERMISSIONS } from "./permission";
import { Role } from "./role";
export const ROLE_PERMISSIONS: Record<Role, readonly string[]> = {
    ADMIN: ["*"],
    USER: [
        PERMISSIONS.PROFILE_VIEW_OWN,
        PERMISSIONS.PROFILE_UPDATE_OWN,
        PERMISSIONS.TEST_VIEW,
        PERMISSIONS.BOOKING_CREATE,
        PERMISSIONS.BOOKING_VIEW_OWN,
        PERMISSIONS.PAYMENT_CREATE,
        PERMISSIONS.PAYMENT_VIEW_OWN,
        PERMISSIONS.REPORT_VIEW_OWN,
    ],
    
    LAB_STAFF: [
        PERMISSIONS.PROFILE_VIEW_OWN,
        PERMISSIONS.PROFILE_UPDATE_OWN,
        PERMISSIONS.TEST_VIEW,
        PERMISSIONS.BOOKING_VIEW_ALL,
        PERMISSIONS.REPORT_UPLOAD,
        PERMISSIONS.REPORT_VIEW_ALL,
    ],
    
}