import { TIME_SLOTS, BOOKING_CONSTANTS } from "../constants";

export const BOOKING_CONFIG = {
    LAB_CAPACITY_PER_SLOT: BOOKING_CONSTANTS.LAB_CAPACITY_PER_SLOT,
    AVAILABLE_TIME_SLOTS: TIME_SLOTS,
    MAX_ADVANCE_BOOKING_DAYS: BOOKING_CONSTANTS.MAX_ADVANCE_BOOKING_DAYS,
    MIN_HOURS_BEFORE_BOOKING: BOOKING_CONSTANTS.MIN_HOURS_BEFORE_BOOKING,
};